name: muscle_track
description: "Muscle Track es tu app ideal para llevar un registro detallado de tus entrenamientos y progresos en el gimnasio."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  dio_http_formatter: ^3.3.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  formz: ^0.8.0
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.14
  carousel_slider: ^5.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  retrofit: ^4.4.0
  logger: ^2.4.0 
  shared_preferences: ^2.3.3
  multiple_result: ^5.1.0
  riverpod_annotation: ^2.6.1
  alert_info: ^0.0.2
  firebase_core: ^3.8.1
  firebase_crashlytics: ^4.2.0
  firebase_analytics: ^11.3.6
  intl: ^0.20.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5
  riverpod_generator: ^2.6.3
  launcher_name: ^1.0.2
  flutter_launcher_icons: ^0.14.1
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  android_icon: true
  ios_icon: true
  adaptive_icon_background: "#FF1946FF"
  adaptive_icon_foreground: "assets/icons/icon.png"

launcher_name:
  default: "Muscle Track"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - google_fonts/

flutter_native_splash:
  color: "#1946FF"
  image: assets/images/logo.png
  android: true
  ios: true
  web: false

  android_12:
    image: assets/images/logo.png